apiVersion: v1
kind: Service
metadata:
  name: {{ include "enclave.backend.fullname" . }}
  labels:
    {{- include "enclave.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "enclave.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
